# Generated by Django 3.2 on 2023-06-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230529_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='income_monhtly',
            new_name='income_monthly',
        ),
    ]
